# Basic Site Information
title: walterlv
author: walterlv
post_author: 吕毅
# description: Windows 10 Developer
mail: walterlv@outlook.com
about: Windows 10 Developer

# Site Appearance
logo: /static/img/avatar.png
markdown: kramdown
highlighter: rouge

# Site Urls
baseurl: ""
url: "https://walterlv.github.io"

# Social Accounts
github: https://github.com/walterlv
share:
  twitter_username: _lvyi_

# Visit Analysis
analytics:
  google: UA-108101550-1
  cnzz: cnzz_stat_icon_1264408226
disqus:
  name: walterlv
gitment:
  owner: walterlv
  client_id: 9a8b44a07f269679e9b5
  client_secret: 3412cef75373074fd43b62462a7adef7ad1e2127
  repo: walterlv.github.io
leancloud:
  appid: 2NpLNUTfjU4ey5wOeWPPiXXL-gzGzoHsz
  appkey: OeA2qCtXi7ifv96UbMQ4J1kn

enableTags: true
tagarray: []

# Post Settings
excerpt_separator: ---
paginate: 15
per_page: 15
paginate_path: "/blog/page:num/"
collections:
  articles:
    output: true
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "吕毅"
      permalink: "/post/:title.html"
  - scope:
      path: "_articles"
      type: "articles"
    values:
      layout: "post"
      author: "吕毅"
      permalink: "/article/:title.html"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# Others
exclude: ['package.json', 'src', 'node_modules']
