# Site Metadata
title: walterlv
email: walterlv@outlook.com
description: Windows 10 Developer
description_detail: >
  Write code for Windows 10, with UWP, WPF, Xamarin, Visual Studio, Visual Studio Code, iOS, html, TypeScript.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://walterlv.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social Info
twitter_username: _lvyi_
facebook_username: Xblero
github_username:  walterlv

# Build Settings
excerpt_separator: ---
paginate: 15
paginate_path: "/blog/page:num"
markdown: kramdown
theme: minima
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Content Collection
collections:
  article:
    output: true

# Content Template
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "吕毅"
      categories: "post"
      permalink: "/:categories/:title.html"
  - scope:
      path: "_article"
      type: "article"
    values:
      layout: "post"
      author: "吕毅"
      categories: "article"
      permalink: "/:categories/:title.html"
