title: walterlv
description: Windows 10 Developer
author: walterlv
post_author: 吕毅
mail: walterlv@outlook.com
logo: /static/img/avatar.png
github: https://github.com/walterlv
about: Windows 10 Developer

baseurl: ""
url: "https://walterlv.github.io"

allowsearch: true

analytics:
  google: UA-108101550-1
  cnzz: cnzz_stat_icon_1264408226
disqus:
  name: walterlv
gitment:
  owner: walterlv
  client_id: 9a8b44a07f269679e9b5
  client_secret: 3412cef75373074fd43b62462a7adef7ad1e2127
  repo: walterlv.github.io
leancloud:
  appid: 2NpLNUTfjU4ey5wOeWPPiXXL-gzGzoHsz
  appkey: OeA2qCtXi7ifv96UbMQ4J1kn

share:
  twitter_username: _lvyi_


enableTags: true
tagarray: []

excerpt_separator: ---
paginate: 15
per_page: 15
paginate_path: "/blog/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]

# Content Collection
collections:
  articles:
    output: true

# Content Template
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "吕毅"
      permalink: "/post/:title.html"
  - scope:
      path: "_articles"
      type: "articles"
    values:
      layout: "post"
      author: "吕毅"
      permalink: "/article/:title.html"
